-- PulsePlate Alpha database schema for Supabase/PostgreSQL.
-- Run this in Supabase SQL Editor before using the alpha.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'PulsePlate User',
  email text,
  role text not null default 'user' check (role in ('user','trainer')),
  business_name text,
  primary_goal text not null default 'health' check (primary_goal in ('lose','maintain','gain','health','custom')),
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.nutrition_goals (
  user_id uuid primary key references auth.users(id) on delete cascade,
  calorie_goal integer not null default 2050 check (calorie_goal between 500 and 10000),
  protein_goal numeric not null default 147 check (protein_goal between 0 and 1000),
  carbs_goal numeric not null default 230 check (carbs_goal between 0 and 1500),
  fat_goal numeric not null default 68 check (fat_goal between 0 and 500),
  current_weight numeric,
  goal_weight numeric,
  updated_at timestamptz not null default now()
);

create table if not exists public.food_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  logged_date date not null default current_date,
  meal text not null default 'Meal',
  food_name text not null,
  serving text not null default '1 serving',
  fdc_id bigint,
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  created_at timestamptz not null default now()
);


-- Add onboarding/trainer fields to existing projects created before this version.
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists business_name text;
alter table public.profiles add column if not exists primary_goal text not null default 'health';
alter table public.profiles add column if not exists onboarding_complete boolean not null default false;

create index if not exists food_entries_user_date_idx on public.food_entries(user_id, logged_date, created_at);

alter table public.profiles enable row level security;
alter table public.nutrition_goals enable row level security;
alter table public.food_entries enable row level security;

-- Make this schema safe to run more than once during development.
drop policy if exists "profiles own row" on public.profiles;
drop policy if exists "profiles insert own row" on public.profiles;
drop policy if exists "profiles update own row" on public.profiles;
drop policy if exists "goals own row" on public.nutrition_goals;
drop policy if exists "goals insert own row" on public.nutrition_goals;
drop policy if exists "goals update own row" on public.nutrition_goals;
drop policy if exists "food entries own rows" on public.food_entries;
drop policy if exists "food entries insert own rows" on public.food_entries;
drop policy if exists "food entries update own rows" on public.food_entries;
drop policy if exists "food entries delete own rows" on public.food_entries;


create policy "profiles own row" on public.profiles for select using (auth.uid() = id);
create policy "profiles insert own row" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles update own row" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "goals own row" on public.nutrition_goals for select using (auth.uid() = user_id);
create policy "goals insert own row" on public.nutrition_goals for insert with check (auth.uid() = user_id);
create policy "goals update own row" on public.nutrition_goals for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "food entries own rows" on public.food_entries for select using (auth.uid() = user_id);
create policy "food entries insert own rows" on public.food_entries for insert with check (auth.uid() = user_id);
create policy "food entries update own rows" on public.food_entries for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "food entries delete own rows" on public.food_entries for delete using (auth.uid() = user_id);


-- Social, messaging, and controlled meal-sharing features.
create table if not exists public.friend_connections (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  share_meals boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id),
  unique (requester_id, addressee_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> recipient_id)
);

create unique index if not exists friend_connections_pair_unique on public.friend_connections (least(requester_id, addressee_id), greatest(requester_id, addressee_id));
create index if not exists friend_connections_requester_idx on public.friend_connections(requester_id, status);
create index if not exists friend_connections_addressee_idx on public.friend_connections(addressee_id, status);
create index if not exists messages_conversation_idx on public.messages(sender_id, recipient_id, created_at);

-- Backfill email for profiles that existed before email discovery was added.
update public.profiles p set email = u.email from auth.users u where p.id = u.id and (p.email is null or p.email <> u.email);

alter table public.friend_connections enable row level security;
alter table public.messages enable row level security;

-- Signed-in users may discover profiles. Email is intentionally included because PulsePlate's friend search
-- uses email as a secondary identifier. This can be tightened later with a privacy setting.
drop policy if exists "authenticated profiles discovery" on public.profiles;
create policy "authenticated profiles discovery" on public.profiles for select to authenticated using (true);

drop policy if exists "friends participants read" on public.friend_connections;
drop policy if exists "friends requester insert" on public.friend_connections;
drop policy if exists "friends participants update" on public.friend_connections;
create policy "friends participants read" on public.friend_connections for select to authenticated using (auth.uid() = requester_id or auth.uid() = addressee_id);
create policy "friends requester insert" on public.friend_connections for insert to authenticated with check (auth.uid() = requester_id);
create policy "friends participants update" on public.friend_connections for update to authenticated using (auth.uid() = requester_id or auth.uid() = addressee_id) with check (auth.uid() = requester_id or auth.uid() = addressee_id);

drop policy if exists "messages participants read" on public.messages;
drop policy if exists "messages sender insert" on public.messages;
drop policy if exists "messages participants update" on public.messages;
create policy "messages participants read" on public.messages for select to authenticated using (auth.uid() = sender_id or auth.uid() = recipient_id);
create policy "messages sender insert" on public.messages for insert to authenticated with check (auth.uid() = sender_id and exists (select 1 from public.friend_connections c where c.status = 'accepted' and ((c.requester_id = sender_id and c.addressee_id = recipient_id) or (c.requester_id = recipient_id and c.addressee_id = sender_id))));
create policy "messages participants update" on public.messages for update to authenticated using (auth.uid() = sender_id or auth.uid() = recipient_id) with check (auth.uid() = sender_id or auth.uid() = recipient_id);

-- Food visibility: own food is always visible. A trainer can see an accepted client's food automatically.
-- Non-trainer friends can see it only when the client enabled share_meals for that connection.
drop policy if exists "food entries own rows" on public.food_entries;
create policy "food entries own rows" on public.food_entries for select to authenticated using (
  auth.uid() = user_id
  or exists (
    select 1
    from public.friend_connections c
    join public.profiles viewer on viewer.id = auth.uid()
    join public.profiles owner on owner.id = food_entries.user_id
    where c.status = 'accepted'
      and ((c.requester_id = auth.uid() and c.addressee_id = food_entries.user_id)
        or (c.requester_id = food_entries.user_id and c.addressee_id = auth.uid()))
      and ((viewer.role = 'trainer' and owner.role = 'user') or c.share_meals = true)
  )
);
