-- PulsePlate Alpha database schema for Supabase/PostgreSQL.
-- Run this in Supabase SQL Editor before using the alpha.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'PulsePlate User',
  email text,
  role text not null default 'user' check (role in ('user','trainer')),
  business_name text,
  primary_goal text not null default 'health' check (primary_goal in ('lose','maintain','gain','health','custom')),
  onboarding_complete boolean not null default false,
  message_notifications_enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.nutrition_goals (
  user_id uuid primary key references auth.users(id) on delete cascade,
  calorie_goal integer not null default 2050 check (calorie_goal between 500 and 10000),
  protein_goal numeric not null default 147 check (protein_goal between 0 and 1000),
  carbs_goal numeric not null default 230 check (carbs_goal between 0 and 1500),
  fat_goal numeric not null default 68 check (fat_goal between 0 and 500),
  current_weight numeric,
  goal_weight numeric,
  updated_at timestamptz not null default now()
);

create table if not exists public.food_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  logged_date date not null default current_date,
  meal text not null default 'Meal',
  food_name text not null,
  serving text not null default '1 serving',
  fdc_id bigint,
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  created_at timestamptz not null default now()
);


-- Add onboarding/trainer fields to existing projects created before this version.
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists business_name text;
alter table public.profiles add column if not exists primary_goal text not null default 'health';
alter table public.profiles add column if not exists onboarding_complete boolean not null default false;
alter table public.profiles add column if not exists message_notifications_enabled boolean not null default true;

create index if not exists food_entries_user_date_idx on public.food_entries(user_id, logged_date, created_at);

alter table public.profiles enable row level security;
alter table public.nutrition_goals enable row level security;
alter table public.food_entries enable row level security;

-- Make this schema safe to run more than once during development.
drop policy if exists "profiles own row" on public.profiles;
drop policy if exists "profiles insert own row" on public.profiles;
drop policy if exists "profiles update own row" on public.profiles;
drop policy if exists "goals own row" on public.nutrition_goals;
drop policy if exists "goals insert own row" on public.nutrition_goals;
drop policy if exists "goals update own row" on public.nutrition_goals;
drop policy if exists "food entries own rows" on public.food_entries;
drop policy if exists "food entries insert own rows" on public.food_entries;
drop policy if exists "food entries update own rows" on public.food_entries;
drop policy if exists "food entries delete own rows" on public.food_entries;


create policy "profiles own row" on public.profiles for select using (auth.uid() = id);
create policy "profiles insert own row" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles update own row" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "goals own row" on public.nutrition_goals for select using (auth.uid() = user_id);
create policy "goals insert own row" on public.nutrition_goals for insert with check (auth.uid() = user_id);
create policy "goals update own row" on public.nutrition_goals for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "food entries own rows" on public.food_entries for select using (auth.uid() = user_id);
create policy "food entries insert own rows" on public.food_entries for insert with check (auth.uid() = user_id);
create policy "food entries update own rows" on public.food_entries for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "food entries delete own rows" on public.food_entries for delete using (auth.uid() = user_id);


-- Social, messaging, and controlled meal-sharing features.
create table if not exists public.friend_connections (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  share_meals boolean not null default false,
  requester_share_meals boolean not null default false,
  addressee_share_meals boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requester_id <> addressee_id),
  unique (requester_id, addressee_id)
);

-- Add per-person meal-sharing controls to existing installations.
alter table public.friend_connections add column if not exists requester_share_meals boolean not null default false;
alter table public.friend_connections add column if not exists addressee_share_meals boolean not null default false;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> recipient_id)
);

create unique index if not exists friend_connections_pair_unique on public.friend_connections (least(requester_id, addressee_id), greatest(requester_id, addressee_id));
create index if not exists friend_connections_requester_idx on public.friend_connections(requester_id, status);
create index if not exists friend_connections_addressee_idx on public.friend_connections(addressee_id, status);
create index if not exists messages_conversation_idx on public.messages(sender_id, recipient_id, created_at);

-- Backfill email for profiles that existed before email discovery was added.
update public.profiles p set email = u.email from auth.users u where p.id = u.id and (p.email is null or p.email <> u.email);

-- Migrate legacy connection-level sharing into per-person sharing.
update public.friend_connections
   set requester_share_meals = true,
       addressee_share_meals = true
 where share_meals = true
   and (requester_share_meals = false or addressee_share_meals = false);

-- Existing trainer/client connections also follow the mandatory client-sharing rule.
update public.friend_connections c
set requester_share_meals = true
where c.status = 'accepted'
  and exists (select 1 from public.profiles p where p.id = c.requester_id and p.role = 'user')
  and exists (select 1 from public.profiles p where p.id = c.addressee_id and p.role = 'trainer');

update public.friend_connections c
set addressee_share_meals = true
where c.status = 'accepted'
  and exists (select 1 from public.profiles p where p.id = c.requester_id and p.role = 'trainer')
  and exists (select 1 from public.profiles p where p.id = c.addressee_id and p.role = 'user');

alter table public.friend_connections enable row level security;
alter table public.messages enable row level security;

-- Signed-in users may discover profiles. Email is intentionally included because PulsePlate's friend search
-- uses email as a secondary identifier. This can be tightened later with a privacy setting.
drop policy if exists "authenticated profiles discovery" on public.profiles;
create policy "authenticated profiles discovery" on public.profiles for select to authenticated using (true);

drop policy if exists "friends participants read" on public.friend_connections;
drop policy if exists "friends requester insert" on public.friend_connections;
drop policy if exists "friends participants update" on public.friend_connections;
create policy "friends participants read" on public.friend_connections for select to authenticated using (auth.uid() = requester_id or auth.uid() = addressee_id);
create policy "friends requester insert" on public.friend_connections for insert to authenticated with check (auth.uid() = requester_id);
create policy "friends participants update" on public.friend_connections for update to authenticated using (auth.uid() = requester_id or auth.uid() = addressee_id) with check (auth.uid() = requester_id or auth.uid() = addressee_id);

drop policy if exists "messages participants read" on public.messages;
drop policy if exists "messages sender insert" on public.messages;
drop policy if exists "messages participants update" on public.messages;
create policy "messages participants read" on public.messages for select to authenticated using (auth.uid() = sender_id or auth.uid() = recipient_id);
create policy "messages sender insert" on public.messages for insert to authenticated with check (auth.uid() = sender_id and exists (select 1 from public.friend_connections c where c.status = 'accepted' and ((c.requester_id = sender_id and c.addressee_id = recipient_id) or (c.requester_id = recipient_id and c.addressee_id = sender_id))));
create policy "messages participants update" on public.messages for update to authenticated using (auth.uid() = sender_id or auth.uid() = recipient_id) with check (auth.uid() = sender_id or auth.uid() = recipient_id);

-- Food visibility: own food is always visible. A trainer can see an accepted client's food automatically.
-- For every other direction, the owner of the food log must explicitly enable their
-- own sharing flag on the connection. Trainers may therefore share their own meals
-- with clients, and two Personal users can independently share their meals with each other.
drop policy if exists "food entries own rows" on public.food_entries;
create policy "food entries own rows" on public.food_entries for select to authenticated using (
  auth.uid() = user_id
  or exists (
    select 1
    from public.friend_connections c
    join public.profiles viewer on viewer.id = auth.uid()
    join public.profiles owner on owner.id = food_entries.user_id
    where c.status = 'accepted'
      and ((c.requester_id = auth.uid() and c.addressee_id = food_entries.user_id)
        or (c.requester_id = food_entries.user_id and c.addressee_id = auth.uid()))
      and (
        (viewer.role = 'trainer' and owner.role = 'user')
        or case
          when c.requester_id = food_entries.user_id then c.requester_share_meals
          else c.addressee_share_meals
        end = true
      )
  )
);


-- Meal sharing is controlled independently by each person on a connection.
-- Personal users and trainers can choose whether to share their own meals, except
-- that a Personal user connected to a Personal Trainer must share their food log
-- with that trainer and cannot disable that direction of sharing. The trainer's
-- own meal sharing remains independently controlled by the trainer.
-- The legacy share_meals column is retained for compatibility.
revoke update on public.friend_connections from authenticated;
grant update (status) on public.friend_connections to authenticated;

drop function if exists public.set_meal_sharing(bigint, boolean);
create or replace function public.set_meal_sharing(connection_id bigint, enabled boolean)
returns public.friend_connections
language plpgsql
security definer
set search_path = public
as $$
declare
  connection_row public.friend_connections;
  my_role text;
  other_role text;
  other_user_id uuid;
begin
  select *
    into connection_row
    from public.friend_connections
   where id = connection_id
     and status = 'accepted'
     and (requester_id = auth.uid() or addressee_id = auth.uid());

  if connection_row.id is null then
    raise exception 'Accepted friend connection not found.';
  end if;

  other_user_id := case
    when connection_row.requester_id = auth.uid() then connection_row.addressee_id
    else connection_row.requester_id
  end;

  select role into my_role from public.profiles where id = auth.uid();
  select role into other_role from public.profiles where id = other_user_id;

  -- A Personal user connected to a Personal Trainer must share their own
  -- food log with that trainer. The trainer can still independently choose
  -- whether to share the trainer's own food log with the client.
  update public.friend_connections
     set requester_share_meals = case
           when requester_id = auth.uid() then
             case
               when my_role = 'user' and other_role = 'trainer' then true
               else enabled
             end
           else requester_share_meals
         end,
         addressee_share_meals = case
           when addressee_id = auth.uid() then
             case
               when my_role = 'user' and other_role = 'trainer' then true
               else enabled
             end
           else addressee_share_meals
         end,
         share_meals = (
           case when requester_id = auth.uid() then enabled else requester_share_meals end
           or case when addressee_id = auth.uid() then enabled else addressee_share_meals end
         ),
         updated_at = now()
   where id = connection_row.id
  returning * into connection_row;

  return connection_row;
end;
$$;

grant execute on function public.set_meal_sharing(bigint, boolean) to authenticated;

-- Personal foods, reusable recipes, and private saved meals.
-- Run this section after the existing PulsePlate schema. It is safe to run more than once.
create table if not exists public.user_foods (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  serving_amount numeric not null default 1 check (serving_amount > 0),
  serving_unit text not null default 'serving',
  calories numeric not null default 0 check (calories >= 0),
  protein numeric not null default 0 check (protein >= 0),
  carbs numeric not null default 0 check (carbs >= 0),
  fat numeric not null default 0 check (fat >= 0),
  fdc_id bigint,
  source text not null default 'manual' check (source in ('manual','usda')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  servings numeric not null default 1 check (servings > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recipe_items (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  food_name text not null,
  serving text not null,
  fdc_id bigint,
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.saved_meals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_meal_items (
  id bigint generated by default as identity primary key,
  saved_meal_id bigint not null references public.saved_meals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  food_name text not null,
  serving text not null,
  fdc_id bigint,
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists user_foods_user_name_idx on public.user_foods(user_id, name);
create index if not exists recipes_user_name_idx on public.recipes(user_id, name);
create index if not exists recipe_items_recipe_idx on public.recipe_items(recipe_id);
create index if not exists saved_meals_user_name_idx on public.saved_meals(user_id, name);
create index if not exists saved_meal_items_meal_idx on public.saved_meal_items(saved_meal_id);

alter table public.user_foods enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_items enable row level security;
alter table public.saved_meals enable row level security;
alter table public.saved_meal_items enable row level security;

drop policy if exists "user foods own rows" on public.user_foods;
drop policy if exists "user foods insert own rows" on public.user_foods;
drop policy if exists "user foods update own rows" on public.user_foods;
drop policy if exists "user foods delete own rows" on public.user_foods;
create policy "user foods own rows" on public.user_foods for select to authenticated using (auth.uid() = user_id);
create policy "user foods insert own rows" on public.user_foods for insert to authenticated with check (auth.uid() = user_id);
create policy "user foods update own rows" on public.user_foods for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "user foods delete own rows" on public.user_foods for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "recipes own rows" on public.recipes;
drop policy if exists "recipes insert own rows" on public.recipes;
drop policy if exists "recipes update own rows" on public.recipes;
drop policy if exists "recipes delete own rows" on public.recipes;
create policy "recipes own rows" on public.recipes for select to authenticated using (auth.uid() = user_id);
create policy "recipes insert own rows" on public.recipes for insert to authenticated with check (auth.uid() = user_id);
create policy "recipes update own rows" on public.recipes for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "recipes delete own rows" on public.recipes for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "recipe items own rows" on public.recipe_items;
drop policy if exists "recipe items insert own rows" on public.recipe_items;
drop policy if exists "recipe items update own rows" on public.recipe_items;
drop policy if exists "recipe items delete own rows" on public.recipe_items;
create policy "recipe items own rows" on public.recipe_items for select to authenticated using (auth.uid() = user_id);
create policy "recipe items insert own rows" on public.recipe_items for insert to authenticated with check (auth.uid() = user_id and exists (select 1 from public.recipes r where r.id = recipe_items.recipe_id and r.user_id = auth.uid()));
create policy "recipe items update own rows" on public.recipe_items for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "recipe items delete own rows" on public.recipe_items for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "saved meals own rows" on public.saved_meals;
drop policy if exists "saved meals insert own rows" on public.saved_meals;
drop policy if exists "saved meals update own rows" on public.saved_meals;
drop policy if exists "saved meals delete own rows" on public.saved_meals;
create policy "saved meals own rows" on public.saved_meals for select to authenticated using (auth.uid() = user_id);
create policy "saved meals insert own rows" on public.saved_meals for insert to authenticated with check (auth.uid() = user_id);
create policy "saved meals update own rows" on public.saved_meals for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "saved meals delete own rows" on public.saved_meals for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "saved meal items own rows" on public.saved_meal_items;
drop policy if exists "saved meal items insert own rows" on public.saved_meal_items;
drop policy if exists "saved meal items update own rows" on public.saved_meal_items;
drop policy if exists "saved meal items delete own rows" on public.saved_meal_items;
create policy "saved meal items own rows" on public.saved_meal_items for select to authenticated using (auth.uid() = user_id);
create policy "saved meal items insert own rows" on public.saved_meal_items for insert to authenticated with check (auth.uid() = user_id and exists (select 1 from public.saved_meals m where m.id = saved_meal_items.saved_meal_id and m.user_id = auth.uid()));
create policy "saved meal items update own rows" on public.saved_meal_items for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "saved meal items delete own rows" on public.saved_meal_items for delete to authenticated using (auth.uid() = user_id);


-- Notifications for new messages. Backend/database remains PulsePlate; this is user-facing in MacroSync.
-- User feedback
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'general' check (category in ('general','bug','feature','other')),
  message text not null check (char_length(message) between 1 and 4000),
  created_at timestamptz not null default now()
);
alter table public.feedback enable row level security;
drop policy if exists "feedback insert own rows" on public.feedback;
drop policy if exists "feedback own rows read" on public.feedback;
create policy "feedback insert own rows" on public.feedback for insert to authenticated with check (auth.uid() = user_id);
create policy "feedback own rows read" on public.feedback for select to authenticated using (auth.uid() = user_id);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete cascade,
  type text not null default 'message',
  title text not null default 'New message',
  body text not null,
  message_id bigint references public.messages(id) on delete cascade,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists notifications_recipient_read_idx on public.notifications(recipient_id, read_at, created_at desc);

alter table public.notifications enable row level security;
drop policy if exists "notifications recipient read" on public.notifications;
drop policy if exists "notifications recipient update" on public.notifications;
create policy "notifications recipient read" on public.notifications for select to authenticated using (auth.uid() = recipient_id);
create policy "notifications recipient update" on public.notifications for update to authenticated using (auth.uid() = recipient_id) with check (auth.uid() = recipient_id);

-- Send a message and create its notification atomically. This avoids letting clients fabricate notifications.
drop function if exists public.send_message(uuid, text);
create or replace function public.send_message(p_recipient_id uuid, p_body text)
returns public.messages
language plpgsql
security definer
set search_path = public
as $$
declare
  new_message public.messages;
  connection_exists boolean;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to send messages.';
  end if;

  if p_recipient_id = auth.uid() then
    raise exception 'You cannot message yourself.';
  end if;

  if char_length(trim(coalesce(p_body, ''))) < 1 or char_length(trim(p_body)) > 4000 then
    raise exception 'Message must contain between 1 and 4000 characters.';
  end if;

  select exists (
    select 1 from public.friend_connections c
    where c.status = 'accepted'
      and ((c.requester_id = auth.uid() and c.addressee_id = p_recipient_id)
        or (c.requester_id = p_recipient_id and c.addressee_id = auth.uid()))
  ) into connection_exists;

  if not connection_exists then
    raise exception 'You can only message an accepted friend.';
  end if;

  insert into public.messages(sender_id, recipient_id, body)
  values (auth.uid(), p_recipient_id, trim(p_body))
  returning * into new_message;

  -- Respect the recipient's notification preference. Messaging itself always succeeds.
  if exists (
    select 1 from public.profiles p
    where p.id = p_recipient_id
      and p.message_notifications_enabled = true
  ) then
    insert into public.notifications(recipient_id, sender_id, type, title, body, message_id)
    values (p_recipient_id, auth.uid(), 'message', 'New message', trim(p_body), new_message.id);
  end if;

  return new_message;
end;
$$;

grant execute on function public.send_message(uuid, text) to authenticated;

-- Progress tracking: weight history and body measurements
create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  weight numeric(7,2) not null check (weight > 0),
  logged_date date not null default current_date,
  created_at timestamptz not null default now()
);
create index if not exists weight_logs_user_date_idx on public.weight_logs(user_id, logged_date, created_at);
alter table public.weight_logs enable row level security;
drop policy if exists "weight logs own rows" on public.weight_logs;
drop policy if exists "weight logs insert own rows" on public.weight_logs;
drop policy if exists "weight logs update own rows" on public.weight_logs;
drop policy if exists "weight logs delete own rows" on public.weight_logs;
create policy "weight logs own rows" on public.weight_logs for select to authenticated using (auth.uid() = user_id);
create policy "weight logs insert own rows" on public.weight_logs for insert to authenticated with check (auth.uid() = user_id);
create policy "weight logs update own rows" on public.weight_logs for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "weight logs delete own rows" on public.weight_logs for delete to authenticated using (auth.uid() = user_id);

create table if not exists public.body_measurements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  measurement_type text not null,
  value numeric(8,2) not null check (value > 0),
  unit text not null default 'in' check (unit in ('in','cm')),
  logged_date date not null default current_date,
  created_at timestamptz not null default now()
);
create index if not exists body_measurements_user_type_date_idx on public.body_measurements(user_id, measurement_type, logged_date, created_at);
alter table public.body_measurements enable row level security;
drop policy if exists "body measurements own rows" on public.body_measurements;
drop policy if exists "body measurements insert own rows" on public.body_measurements;
drop policy if exists "body measurements update own rows" on public.body_measurements;
drop policy if exists "body measurements delete own rows" on public.body_measurements;
create policy "body measurements own rows" on public.body_measurements for select to authenticated using (auth.uid() = user_id);
create policy "body measurements insert own rows" on public.body_measurements for insert to authenticated with check (auth.uid() = user_id);
create policy "body measurements update own rows" on public.body_measurements for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "body measurements delete own rows" on public.body_measurements for delete to authenticated using (auth.uid() = user_id);

-- Admin feedback inbox
alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.feedback add column if not exists read_at timestamptz;

-- Link feedback to the public profile so Supabase can resolve
-- feedback -> profiles in the admin inbox query.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'feedback_user_id_profiles_fkey'
      and conrelid = 'public.feedback'::regclass
  ) then
    alter table public.feedback
      add constraint feedback_user_id_profiles_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade;
  end if;
end $$;

-- Set administrators manually in Supabase SQL Editor, for example:
-- update public.profiles set is_admin = true where email = 'your-email@example.com';

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "feedback admin read" on public.feedback;
drop policy if exists "feedback admin update" on public.feedback;
drop policy if exists "feedback admin delete" on public.feedback;
create policy "feedback admin read" on public.feedback for select to authenticated using (public.is_admin());
create policy "feedback admin update" on public.feedback for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "feedback admin delete" on public.feedback for delete to authenticated using (public.is_admin());
